services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    env_file:
      - .env
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  db_data: