"""add instruction parent

Revision ID: 2200534a7e3a
Revises: e880bf886548
Create Date: 2025-08-21 18:15:43.352520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2200534a7e3a'
down_revision: Union[str, Sequence[str], None] = 'e880bf886548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructions', 'instructions', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('instructions', 'for_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('for_start', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'instructions', type_='foreignkey')
    op.drop_column('instructions', 'parent_id')
    # ### end Alembic commands ###
