"""add field to car

Revision ID: 4a80d54c4f57
Revises: b777b2e29b7e
Create Date: 2025-08-28 22:23:05.309958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a80d54c4f57'
down_revision: Union[str, Sequence[str], None] = 'b777b2e29b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('is_selected_main', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'is_selected_main')
    # ### end Alembic commands ###
