"""delete parent

Revision ID: 55a1f440454e
Revises: 2200534a7e3a
Create Date: 2025-08-21 18:37:24.579307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a1f440454e'
down_revision: Union[str, Sequence[str], None] = '2200534a7e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('instructions_parent_id_fkey'), 'instructions', type_='foreignkey')
    op.drop_column('instructions', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('instructions_parent_id_fkey'), 'instructions', 'instructions', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
