"""edit models

Revision ID: 614167b3f226
Revises: 55a1f440454e
Create Date: 2025-08-26 13:39:42.352757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614167b3f226'
down_revision: Union[str, Sequence[str], None] = '55a1f440454e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_premium')
    op.drop_column('cars', 'is_deleted')
    # ### end Alembic commands ###
