"""add field to car

Revision ID: 67ff1332e69f
Revises: 4a80d54c4f57
Create Date: 2025-08-28 22:39:42.471923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ff1332e69f'
down_revision: Union[str, Sequence[str], None] = '4a80d54c4f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refuel_records', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refuel_records', 'created_at')
    # ### end Alembic commands ###
