"""add purchase comment

Revision ID: 738fafd4c260
Revises: 555b5cf575cb
Create Date: 2025-09-18 17:43:44.497835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738fafd4c260'
down_revision: Union[str, Sequence[str], None] = '555b5cf575cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'comment')
    # ### end Alembic commands ###
