"""q

Revision ID: 992d3a7b8ce2
Revises: 4159e029c1a8
Create Date: 2025-09-13 17:05:27.837582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992d3a7b8ce2'
down_revision: Union[str, Sequence[str], None] = '4159e029c1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cars_user_id_is_selected_main_key'), 'cars', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cars_user_id_is_selected_main_key'), 'cars', ['user_id', 'is_selected_main'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
