"""add refuel

Revision ID: b777b2e29b7e
Revises: 0a4cda9cba63
Create Date: 2025-08-28 20:55:03.806369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b777b2e29b7e'
down_revision: Union[str, Sequence[str], None] = '0a4cda9cba63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.Enum('92', '95', '98', '100', 'Дизель', 'Газ', 'Электро', name='fueltypeenum'), nullable=True),
    sa.Column('gas_station', sa.Enum('Лукойл', 'Роснефть', 'Газпромнефть', 'Татнефть', 'Shell', 'BP', 'Другая', name='gasstationtypeenum'), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('full_tank', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refuel_records')
    # ### end Alembic commands ###
