"""add par for purchase

Revision ID: c9ae292dd82a
Revises: aeae01625ea7
Create Date: 2025-09-18 19:52:14.898144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ae292dd82a'
down_revision: Union[str, Sequence[str], None] = 'aeae01625ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'car_id')
    # ### end Alembic commands ###
