"""add color to car

Revision ID: e880bf886548
Revises: 1d3ff6a5ed89
Create Date: 2025-08-20 19:53:51.640370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e880bf886548'
down_revision: Union[str, Sequence[str], None] = '1d3ff6a5ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'color')
    # ### end Alembic commands ###
