"""edit refuel_record

Revision ID: f87db4632cb7
Revises: 2c463b2ecf94
Create Date: 2025-08-29 17:18:35.071735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87db4632cb7'
down_revision: Union[str, Sequence[str], None] = '2c463b2ecf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refuel_records', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('refuel_records', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refuel_records', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('refuel_records', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
